using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using UnityEngine;

public class MainMenuControllerClient : MonoBehaviour
{
	public GameObject MainMenu;
    public GameObject HowToPlayMenu;
    public GameObject HowToPlayMenu_aim;
    public GameObject HowToPlayMenu_inventory;

	//On Awake
	private void Awake ()
	{
		MainMenu.SetActive (true);
        HowToPlayMenu.SetActive(false);
        HowToPlayMenu_aim.SetActive (false);
        HowToPlayMenu_inventory.SetActive(false);
    }
		
	//Main Menu Options
	public void OnPlayClick ()
	{
		UnityEngine.SceneManagement.SceneManager.LoadScene ("LoginScreen");
	}

	public void OnTutorialClick ()
	{
		MainMenu.SetActive (false);
        HowToPlayMenu.SetActive (true);
	}

    public void OnTutorialContinueClick()
    {
        HowToPlayMenu.SetActive(false);
        HowToPlayMenu_aim.SetActive(true);
    }

    public void OnTutorialContinueAimClick ()
	{
        HowToPlayMenu_aim.SetActive(false);
        HowToPlayMenu_inventory.SetActive(true);
    }

    public void OnTutorialContinueInventroyClick()
    {
        UnityEngine.SceneManagement.SceneManager.LoadScene("TuteLevelOne");
    }

    public void OnBacktomainmenuClick()
    {
        HowToPlayMenu.SetActive(false);
        HowToPlayMenu_aim.SetActive(false);
        HowToPlayMenu_inventory.SetActive(false);
        MainMenu.SetActive(true);
    }

}
